name: Publish Experimental Packages
description: Bumps the version of an npm package and publishes it with an experimental tag.

on:
  workflow_call:
    inputs:
      package_dir:
        description: Directory of the Package to Publish
        required: true
        default: './'

outputs:
  VERSION_TAG:
    description: Generated Experimental Version Tag for This Package
    value: ${{ steps.version-tag.outputs.VERSION_TAG }}

runs:
  using: composite
  steps:
    - name: Construct Experimental Version Tag
      id: version-tag
      shell: bash
      run: |
        BRANCH_NAME=$(echo "${GITHUB_HEAD_REF}" | sed -r 's/([a-z0-9])([A-Z])/\1-\L\2/g' | sed 's/_/-/g' | sed 's/\//-/g')
        VERSION_TAG="${BRANCH_NAME}-experimental-${GITHUB_RUN_NUMBER}"
        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_OUTPUT

    - name: Bump Version in ${{ inputs.package_dir }}
      shell: bash
      run: |
        cd "${{ inputs.package_dir }}"
        PACKAGE_NAME=$(jq -r .name package.json)
        PACKAGE_VERSION=$(jq -r .version package.json)
        echo "PACKAGE_NAME=${PACKAGE_NAME}" >> $GITHUB_ENV
        NEW_VERSION="${PACKAGE_VERSION%-*}-${VERSION_TAG}"
        npm version "${NEW_VERSION}" --no-git-tag-version

    - name: Publish to npm
      shell: bash
      run: |
        cd "${{ inputs.package_dir }}"
        npm publish --tag="${VERSION_TAG}"