name: Validate

on:
  workflow_call:
    inputs:
      package_dir:
        description: 'Directory of the package to validate'
        required: false
        default: './'
        type: string

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.34

      - name: Install Dependencies
        run: |
          cd ${{ inputs.package_dir }}
          bun install

      - name: Lint
        run: |
          cd ${{ inputs.package_dir }}
          bun run lint

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.34

      - name: Install Dependencies
        run: |
          cd ${{ inputs.package_dir }}
          bun install

      - name: Test
        run: |
          cd ${{ inputs.package_dir }}
          bun test